### ISSUE TITLE
signature spoofing works not in microg

### ISSUE THREAD

**Issue by Mojk9** [whew-inc/FakeGApps#16]
Hi, i have android 7.1, dreamland 2100, nift4's microg installer 3 and fakegapps 4.2 enabled in dreamland, but signature spoofing works not. Then i try with microg installer 2.3.6-0 and the fakegapps version from thermatk but same problem.

**Comment by fillwithjoy1** [comment]
Honestly, you should use this since it works reliably up to Android 10 https://github.com/Nanolx/NanoDroid

**Comment by Mojk9** [comment]
No, fakegapps works perfectly, we just had to activate the global mode in dreamland.

**Comment by Mojk9** [comment]
No, fakegapps works perfectly, we just had to activate the global mode in dreamland.
