### ISSUE TITLE
Does not spoof on Android 14

### ISSUE THREAD

**Issue by Nefatiti** [whew-inc/FakeGApps#19]
FakeGApps fails to spoof the signature on Android 14 (Lineage OS 21).

**Comment by whew-inc** [comment]
Seems like the original way to hook in older versions doesn't work anymore. The apk here will hook in a14 the same way it does in a13:
[app-debug.zip](https://github.com/whew-inc/FakeGApps/files/13328349/app-debug.zip)

Thanks for reporting back with results. If it works I'll push a new version.

**Comment by Nefatiti** [comment]
Thanks for your swift reply. Tested, and the FakeGapps 5.apk is spoofing fine on LOS 21 (A14).
![SigSpoof](https://github.com/whew-inc/FakeGApps/assets/76875726/1ea8bf66-3e83-4ba5-b90e-6ed153b89f05)
