### ISSUE TITLE
3.0 release not working on android 12

### ISSUE THREAD

**Issue by giga** [whew-inc/FakeGApps#2]
At title says, 3.0 release not working on android 12 with lsposed, even when activating the module for all apps. Previous release is working.

**Comment by diamant711** [comment]
I have exactly the same problem, are there any updates?

**Comment by whew-inc** [comment]
@giga @diamant711 As LSposed and EdXposed have discontinued development in favor of Zygisk, it's best to migrate to that... but right now I don't have the time to learn the new framework/apis.

You don't lose much by using the previous version.

**Comment by nift4** [comment]
LSPosed is still alive and Zygisk is a replacement for Riru, not for LSPosed.

**Comment by nift4** [comment]
Fixed in my fork: https://github.com/nift4/FakeGApps/releases/tag/3.1
