### ISSUE TITLE
Not working on HarmonyOS 2.0

### ISSUE THREAD

**Issue by Tobim6** [whew-inc/FakeGApps#26]
Hello its not working
![Screenshot_20241223_215505_com android shell](https://github.com/user-attachments/assets/5706735e-1e82-442d-9c6a-c1b3892d3c24)
![Screenshot_20241223_215638_com android shell](https://github.com/user-attachments/assets/8476b282-5a7d-4718-9236-53b91ca1fea7)
![IMG_20241223_215237_943](https://github.com/user-attachments/assets/38722808-d297-489d-88a0-7177a8f4ffce)
![Screenshot_20241223_220014_com google android gms](https://github.com/user-attachments/assets/b7282a71-5d75-4a46-84f3-8bc40197a068)

**Comment by gilbsgilbs** [comment]
HarmonyOS 2.0 looks old, so you're probably hitting [this](https://github.com/whew-inc/FakeGApps/pull/25). Wait for the next release or build the module yourself. Also, "Hello it's not working" is hardly a useful issue description.

**Comment by Tobim6** [comment]
Thanks friend

**Comment by whew-inc** [comment]
I have pushed a new release @Tobim6.
