### ISSUE TITLE
Add this module to LSPosed repo

### ISSUE THREAD

**Issue by Dev0110** [whew-inc/FakeGApps#3]
Hello there,
It would be useful to submit this module to lsposed repo, to make the installation easier.
[https://github.com/Xposed-Modules-Repo/submission](https://github.com/Xposed-Modules-Repo/submission) 
Thanks for your work on this module!

**Comment by whew-inc** [comment]
I submitted the module :)

https://modules.lsposed.org/module/inc.whew.android.fakegapps
https://github.com/Xposed-Modules-Repo/inc.whew.android.fakegapps

**Comment by Dev0110** [comment]
Thanks !
