### ISSUE TITLE
MicroG not recognized by other apps.

### ISSUE THREAD

**Issue by j0110** [whew-inc/FakeGApps#9]
Hi,
I'm facing an annoying situation. MicroG in combination with your module used to work on my device. However, now apps won't start because Google services isn't installed on my device. But on MicroG self-check section, everything is correctly ticked...
How to make others apps recognizing microG services ?
Here are LSPosed logs

**Comment by j0110** [comment]
Here are LSPosed logs
[LSPosed.log.zip](https://github.com/whew-inc/FakeGApps/files/9455691/LSPosed.log.zip)

**Comment by j0110** [comment]
Fixed by installing apps from the real playstore, not from aurora store...
Maybe a work is possible on your module to allow the signature from the real play store (I don't really understand the logic behind signature spoofing so maybe I'm totally wrong...).

**Comment by whew-inc** [comment]
The module already spoofs FakeStore's signature and Aurora Store with root install method should take care of app origin. Perhaps you reinstalled Microg somewhere on the way? That tends to mess with apps.

**Comment by j0110** [comment]
I was using Aurora services... Root install method sloved the problem. Thanks !
